trigger:
- main

resources:
- repo: self

pool: mo-cluster-agent-pool

variables:
  DOCKER_HOST: 'unix:///run/user/1000/docker.sock'
  DOCKER_BUILDKIT: 1

  packageName: 'mogenius-k8s-manager'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: main
    steps:
    - script: VERS=$(grep "Ver" $(Build.SourcesDirectory)/version/consts.go | awk -F "\"" {'print $2'})
      displayName: Set version variable
      name: myVersion
  - job: variables_handler
    dependsOn: main
    variables:
      VER: $[ dependencies.main.outputs['myVersion.VERS'] ]
      VERX: $(grep "Ver" $(Build.SourcesDirectory)/version/consts.go | awk -F "\"" {'print $2'})
    steps:
    - script: |
        echo "v: ${VER} - ${VERX} - $(Build.BuildId)"
        echo "x: $(grep "Ver" $(Build.SourcesDirectory)/version/consts.go | awk -F "\"" {'print $2'})"
    - task: CmdLine@2
      displayName: Create version artifact from variables
      inputs:
        script: |
          Y=$(Build.BuildId)
          X=$(grep "Ver" $(Build.SourcesDirectory)/version/consts.go | awk -F "\"" {'print $2'})
          echo "VERSION=${X}" > $(Build.ArtifactStagingDirectory)/pipeline.env
          echo "BUILDID=${Y}" > $(Build.ArtifactStagingDirectory)/build.env
    # echo "##vso[task.setvariable variable=VERSION;]$(VER)" > $(Build.ArtifactStagingDirectory)/pipeline.env
    - script: |
        cat $(Build.ArtifactStagingDirectory)/pipeline.env
      displayName: cat pipeline env
    # - task: CmdLine@2
    #   displayName: Create build artifact from variables
    #   inputs:
    #     script: |
    #       echo "##vso[task.setvariable variable=BUILDID;]$(Build.BuildId)" >  $(Build.ArtifactStagingDirectory)/build.env
    - task: PublishBuildArtifacts@1
      displayName: publish variables
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'variables'
        publishLocation: 'Container'
  - job: Build
    displayName: Build
    steps:
    - bash: |
        #!/bin/bash
        set -x
        ls -lisa
        GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
        COMMIT_HASH=$(git rev-parse --short HEAD)
        GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        BUILD_TIMESTAMP=$(date -Iseconds)
        VERSION=$(grep "Ver" $(Build.SourcesDirectory)/version/consts.go | awk -F "\"" {'print $2'})
        echo $(CR_PAT) | docker login ghcr.io -u beneiltis --password-stdin
        docker build --build-arg NEXT_VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -f Dockerfile -t ghcr.io/mogenius/$(packageName):$VERSION -t ghcr.io/mogenius/$(packageName):latest .
        docker image push ghcr.io/mogenius/$(packageName):$VERSION; docker image push ghcr.io/mogenius/$(packageName):latest
      timeoutInMinutes: 10
      name: dockerBuildPush
      failOnStderr: false
