trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c33e89d2-8471-4f8a-9ea6-068fc3bd2f4b'
  imageRepository: 'mogeniusk8smanager'
  containerRegistry: 'mogenius.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: main
    steps:
    - script: VERSION=$(grep "Ver" $(Build.SourcesDirectory)/version/consts.go | awk -F "\"" {'print $2'})
      displayName: Set version variable
      name: myVersion
  - job: variables_handler
    dependsOn: main
    variables:
      VERSION: $[ dependencies.main.outputs['myVersion.VERSION'] ]
    steps:
    - task: CmdLine@2
      displayName: Create artifact from variables
      inputs:
        script: |
          echo "##vso[task.setvariable variable=VERSION;]$(VERSION)\n##vso[task.setvariable variable=BUILDID;]$(Build.BuildId)" >  $(Build.ArtifactStagingDirectory)/pipeline.env
    - task: PublishBuildArtifacts@1
      displayName: publish variables
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'variables'
        publishLocation: 'Container'
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
