apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.mogenius.io
spec:
  group: mogenius.io
  versions:
    - additionalPrinterColumns:
      - name: Display Name
        jsonPath: .spec.displayName
        type: string
      - name: Created By
        jsonPath: .spec.createdBy
        type: string
      - name: Application Kit Ref
        jsonPath: .spec.applicationKitRef
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                displayName:
                  type: string
                name:
                  type: string
                createdBy:
                  type: string
                applicationKitRefs:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: environments
    singular: environment
    kind: Environment
    shortNames:
    - env
    - envs
