apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationkits.mogenius.io
spec:
  group: mogenius.io
  versions:
    - additionalPrinterColumns:
      - name: Display Name
        jsonPath: .spec.displayName
        type: string
      - name: Created By
        jsonPath: .spec.createdBy
        type: string
      - name: Controller
        jsonPath: .spec.controller
        type: string
      - name: app ID
        jsonPath: .spec.appId
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                displayName:
                  type: string
                createdBy:
                  type: string
                controller:
                  type: string
                appId:
                  type: string
  scope: Namespaced
  names:
    plural: applicationkits
    singular: applicationkit
    kind: ApplicationKit
    shortNames:
    - appkit
    - apk
    - ak
