apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: local-ssl-ingress
  namespace: mogenius
spec:
  rules:
  - host: localdocker.mogenius.io
    http:
      paths:
      - backend:
          service:
            name: distribution-registry-docker-registry
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - localdocker.mogenius.io
    secretName: localdocker.mogenius.io-tls