{{- if .Values.valkey.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-valkey
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  valkey-password: {{ include "lookupSecret" . | quote }}
{{ end }}
