kubernetes:
  cluster_name: BenesTestCluster
  run_in_cluster: false
  default_container_registry: mogenius.azurecr.io

api_server:
  websocket_server: 127.0.0.1
  websocket_path: /ws
  websocket_port: 8080
  api_key: 94E23575-A689-4F88-8D67-215A274F4E6E

misc:
  default_mount_path: /mo-data
  storage_account: monfs
  debug: false
  concurrent_connections: 3
  ignore_namespaces: ["kube-system", "default"]