kubernetes:
  api_key: YOUR_API_KEY
  cluster_name: your-cluster-name
  own_namespace: mogenius
  cluster_mfa_id:
  run_in_cluster: true
  default_container_registry: docker.io

api_server:
  http_server: https://platform-api.mogenius.com
  ws_server: k8s-ws.mogenius.com
  ws_path: /ws

event_server:
  server: k8s-dispatcher.mogenius.com
  path: /ws

misc:
  stage: prod
  default_mount_path: /mo-data
  debug: false
  auto_mount_nfs: true
  log_kubernetes_events: false
  ignore_namespaces: ["kube-system"]
  ignore_resources_backup:
    [
      "events.k8s.io/v1",
      "events.k8s.io/v1beta1",
      "metrics.k8s.io/v1beta1",
      "discovery.k8s.io/v1",
    ]
  check_for_updates: 86400
  helm_index: https://helm.mogenius.com/public/index.yaml
  cluster_provider: BRING_YOUR_OWN
