kubernetes:
  api_key: YOUR_API_KEY
  cluster_name: your-cluster-name
  own_namespace: mogenius
  cluster_mfa_id:
  run_in_cluster: true
  default_container_registry: docker.io

api_server:
  ws_proto: ws
  ws_server: k8s-api.dev.mogenius.com:1337
  ws_path: /ws

event_server:
  server: k8s-api.dev.mogenius.com
  path: /ws
  port: 1338

misc:
  stage: dev
  default_mount_path: /mo-data
  storage_account: monfs
  debug: false
  log_kubernetes_events: false
  concurrent_connections: 1
  ignore_namespaces: ["kube-system", "default"]
  ignore_resources_backup:
    [
      "events.k8s.io/v1",
      "events.k8s.io/v1beta1",
      "metrics.k8s.io/v1beta1",
      "discovery.k8s.io/v1",
    ]
  check_for_updates: 86400
  helm_index: https://helm.mogenius.com/public/index.yaml
