kubernetes:
  api_key: 94E23575-A689-4F88-8D67-215A274F4E6E
  cluster_name: BenesTestCluster
  own_namespace: mogenius
  cluster_mfa_id:
  run_in_cluster: false
  bbolt_db_path: mogenius.db
  bbolt_db_stats_path: mogenius-stats.db
  local_registry_host: mocr.local.mogenius.io

api_server:
  http_server: https://platform-api.dev.mogenius.com
  ws_server: 127.0.0.1:8080
  ws_server_scheme: ws
  ws_path: /ws

event_server:
  server: 127.0.0.1:8080
  scheme: ws
  path: /ws-event

iac:
  repo_url:
  repo_pat:
  polling_interval_secs: 10 # min is 5 
  allow_push: true
  allow_pull: true
  allow_manual_cluster_changes: true
  sync_workloads: ["namespaces", "pods", "deployments", "statefulsets", "services", "ingresses", "configmaps", "secrets", "jobs", "cronjobs", "daemonsets", "networkpolicies"]
  show_diff_in_log: true
  log_changes: true

misc:
  stage: local
  log_format: text # json or text
  log_level: info  # panic, fatal, error, warn, info, debug, trace
  log_incoming_stats: false
  default_mount_path: /mo-data
  debug: true
  debug_log_caller: false
  auto_mount_nfs: true
  log_kubernetes_events: true
  ignore_namespaces: ["kube-system"]
  ignore_resources_backup:
    [
      "events.k8s.io/v1",
      "events.k8s.io/v1beta1",
      "metrics.k8s.io/v1beta1",
      "discovery.k8s.io/v1",
    ]
  check_for_updates: 3600
  helm_index: https://helm.mogenius.com/public/index.yaml
  nfs_pod_prefix: nfs-server-pod

builder:
  max_build_time: 3600      # 1 hour
  max_scan_time: 200        # seconds
  max_data_points: 1000     # history data points
  max_concurrent_builds: 3  # max concurrent builds

git:
  user_email: git@mogenius.com
  user_name: mogenius git-user
  default_branch: main
  add_ignored_file: false
