kubernetes:
  api_key: 94E23575-A689-4F88-8D67-215A274F4E6E
  cluster_name: BenesTestCluster
  own_namespace: mogenius
  cluster_mfa_id:
  run_in_cluster: false
  default_container_registry: mogenius.azurecr.io

api_server:
  proto: http
  server: 127.0.0.1
  path: /ws
  stream_path: /stream-data
  ws_port: 8080
  http_port: 8080

event_server:
  server: 127.0.0.1
  path: /ws-event
  port: 8080

misc:
  stage: local
  default_mount_path: /mo-data
  storage_account: monfs
  debug: true
  log_kubernetes_events: false
  concurrent_connections: 1
  ignore_namespaces: ["kube-system", "default"]
  ignore_resources_backup: ["events.k8s.io/v1", "events.k8s.io/v1beta1", "metrics.k8s.io/v1beta1", "discovery.k8s.io/v1"]
  check_for_updates: 3600
  helm_index: https://helm.mogenius.com/public/index.yaml