kubernetes:
  api_key: YOUR_API_KEY
  cluster_name: your-cluster-name
  cluster_id:
  run_in_cluster: true
  default_container_registry: docker.io
  check_for_node_stats: 1800

api_server:
  server: k8s-api.dev.mogenius.com
  path: /ws
  port: 1337

event_server:
  server: k8s-api.dev.mogenius.com
  path: /ws
  port: 1338

misc:
  default_mount_path: /mo-data
  storage_account: monfs
  debug: false
  concurrent_connections: 3
  ignore_namespaces: ["kube-system", "default"]
  check_for_updates: 86400
  helm_index: https://helm.mogenius.com/public/index.yaml