kubernetes:
  api_key: 94E23575-A689-4F88-8D67-215A274F4E6E
  cluster_name: BenesTestCluster
  own_namespace: mogenius
  cluster_mfa_id:
  run_in_cluster: false
  default_container_registry: mogenius.azurecr.io

api_server:
  server: 127.0.0.1
  path: /ws
  port: 8080

event_server:
  server: 127.0.0.1
  path: /ws
  port: 8080

misc:
  default_mount_path: /mo-data
  storage_account: monfs
  debug: false
  concurrent_connections: 3
  ignore_namespaces: ["kube-system", "default"]
  check_for_updates: 3600
  helm_index: https://helm.mogenius.com/public/index.yaml