kubernetes:
  api_key: 94E23575-A689-4F88-8D67-215A274F4E6E
  cluster_name: BenesTestCluster
  own_namespace: mogenius
  cluster_mfa_id:
  run_in_cluster: false
  default_container_registry: mogenius.azurecr.io

api_server:
  http_server: https://platform-api.dev.mogenius.com
  ws_server: 127.0.0.1:8080
  ws_path: /ws

event_server:
  server: 127.0.0.1:8080
  path: /ws-event

misc:
  stage: local
  default_mount_path: /mo-data
  debug: true
  auto_mount_nfs: true
  log_kubernetes_events: true
  ignore_namespaces: ["kube-system"]
  ignore_resources_backup:
    [
      "events.k8s.io/v1",
      "events.k8s.io/v1beta1",
      "metrics.k8s.io/v1beta1",
      "discovery.k8s.io/v1",
    ]
  check_for_updates: 3600
  helm_index: https://helm.mogenius.com/public/index.yaml
  cluster_provider: BRING_YOUR_OWN
