apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  name: local-ssl-ingress
  namespace: mogenius
spec:
  rules:
  - host: mocr.local.mogenius.io
    http:
      paths:
      - backend:
          service:
            name: distribution-registry-docker-registry
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - '*.local.mogenius.io'
    secretName: local.mogenius.io-tls
