name: Build, Package, Release (Dev & Feature Branches)

on:
  push:
    branches:
      - feat**
      - fix**
      - develop

env:
  IMAGE_NAME: ghcr.io/mogenius/mogenius-k8s-manager-dev
  DOCKERFILE: Dockerfile
  HELMNAME: "mogenius-k8s-manager-dev"
  HELMREPO: "mogenius/helm-k8s-manager"

jobs:
  prepare:
    runs-on: self-hosted-ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Create Sematic Release Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # export HOME=/root
          # git config --system http.sslVerify false
          git config --global user.email "mok8s@mogenius.com"
          git config --global user.name "mok8s"
          git config --global credential.helper cache
          npx semantic-release

  passing-tests:
    
    needs: prepare
    runs-on: [self-hosted, ARM64, k3s-installed]
    continue-on-error: true # tests are not stable yet
    concurrency: 
      group: passing-tests-LOCK
      cancel-in-progress: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # TODO: this should be part of the build / local test logic in some way
      - name: Prepare CRDs
        run: |
          kubectl create namespace mogenius
          helm repo add external-secrets https://charts.external-secrets.io
          helm install external-secrets external-secrets/external-secrets
          kubectl apply -f utils/yaml-templates/crds-applicationkit.yaml
          kubectl apply -f utils/yaml-templates/crds-environments.yaml
          kubectl apply -f utils/yaml-templates/crds-projects.yaml
          
          # helm release is taking some to boot pods
          sleep 30
      - name: Run tests
        run: |
          go mod download
          go clean -testcache
          go test -v ./...
      - name: Clean up k3s
        if: always()
        run: |
          kubectl delete namespace mogenius
          helm uninstall external-secrets

  build-amd64:
    needs: 
      - prepare
      - passing-tests
    runs-on: [self-hosted, X64, XL]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build AMD64 image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -f ${{ env.DOCKERFILE }} --build-arg GOOS=linux --build-arg GOARCH=amd64 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-amd64 -t ${{ env.IMAGE_NAME }}:latest-amd64 .
          
      - name: Push AMD64-linux image
        #if: github.ref == 'refs/heads/develop'
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-amd64


  build-arm64-linux:
    needs: 
      - prepare
      - passing-tests
    runs-on: [self-hosted, ARM64, XL]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64-linux image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build --platform=linux/arm64 -f ${{ env.DOCKERFILE }} --build-arg GOOS=linux --build-arg GOARCH=arm64 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux -t ${{ env.IMAGE_NAME }}:latest-arm64-linux .

      - name: Push AMD64-linux image
        #if: github.ref == 'refs/heads/develop'
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux

  build-arm64:
    needs: 
      - prepare
      - passing-tests
    runs-on: [self-hosted, ARM64, XL]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ARM64 image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -f ${{ env.DOCKERFILE }} --build-arg GOOS=linux --build-arg GOARCH=arm64 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-arm64 -t ${{ env.IMAGE_NAME }}:latest-arm64 .

      - name: Push ARM64 image
        #if: github.ref == 'refs/heads/develop'
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-arm64
  
  build-armv7:
    needs: 
      - prepare
      - passing-tests
    runs-on: [self-hosted, ARM64, XL]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARMv7 image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -f ${{ env.DOCKERFILE }} --platform=linux/arm/v7 --build-arg GOOS=linux --build-arg GOARCH=arm --build-arg GOARM=7 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-arm7 -t ${{ env.IMAGE_NAME }}:latest-arm7 .

      - name: Push ARMv7 image
        #if: github.ref == 'refs/heads/develop'
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-arm7


  merge-images:
    #if: github.ref == 'refs/heads/develop'
    needs: [build-amd64, build-arm64, build-arm64-linux, build-armv7, prepare]
    runs-on: self-hosted-ansible
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge images into a multi-arch manifest
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker manifest create ${{ env.IMAGE_NAME }}:$VERSION \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-amd64 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm7 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:$VERSION
          docker manifest create ${{ env.IMAGE_NAME }}:latest \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-amd64 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm7 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:latest

  helm-chart:
    #if: github.ref == 'refs/heads/develop'
    needs: [prepare, build-amd64, build-arm64, build-arm64-linux, build-armv7, merge-images]
    runs-on: self-hosted-ansible
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set version env
        run: echo "SEMVERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV  

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          # token: ${{ secrets.DOCKERHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.HELMREPO }}
          path: 'helm'        
      
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        id: install

      - name: package and push
        run: |
          cd ./helm
          sed -i -e "s/v1.0.72/${{ env.SEMVERSION }}/" values.yaml
          helm package -d /tmp/ --version ${{ env.SEMVERSION }} .
          curl -XPOST -L -k --data-binary "@/tmp/${{ env.HELMNAME }}-${{ env.SEMVERSION }}.tgz" https://${{ secrets.MO_HELMUSER }}:${{ secrets.MO_HELMPASS }}@helm.mogenius.com/api/public/charts
  
          
      # - name: Grype Vulnerability Scan
      #   run: |
      #     VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
      #     curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      #     curl -sSfL https://raw.githubusercontent.com/mogenius/docs/dev/grype.yaml > grype.yaml
      #     grype -c grype.yaml --add-cpes-if-none --fail-on critical ghcr.io/mogenius/mogenius-k8s-manager-dev:$VERSION

      # currently it is not possible to seperate build and push when using buildx
      # https://github.com/docker/buildx/issues/1152
      # - name: Docker Build & Push
      #   run: |
      #     VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
      #     # docker image push ghcr.io/mogenius/mogenius-k8s-manager-dev:$VERSION; docker image push ghcr.io/mogenius/mogenius-k8s-manager-dev:latest
      #     docker buildx -t ghcr.io/mogenius/mogenius-k8s-manager-dev:$VERSION -t ghcr.io/mogenius/mogenius-k8s-manager-dev:latest --push
