name: Build, Package, Release (Production)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/mogenius/mogenius-k8s-manager
  DOCKERFILE: Dockerfile
  DOCKER_CONFIG: ./.docker
  HELMNAME: "mogenius-k8s-manager"
  HELMREPO: "mogenius/helm-k8s-manager"

jobs:
  prepare:
    runs-on: self-hosted-ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-amd64:
    needs: prepare
    runs-on: [self-hosted, X64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build AMD64 image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -f ${{ env.DOCKERFILE }} --build-arg GITHUB_TOKEN=${{ secrets.SNOOPY_DOWNLOAD_TOKEN }} --build-arg GOOS=linux --build-arg GOARCH=amd64 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-amd64 -t ${{ env.IMAGE_NAME }}:latest-amd64 .
          
      - name: Push AMD64-linux image
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-amd64


  build-arm64-linux:
    needs: prepare
    runs-on: [self-hosted, ARM64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64-linux image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build --platform=linux/arm64 -f ${{ env.DOCKERFILE }} --build-arg GITHUB_TOKEN=${{ secrets.SNOOPY_DOWNLOAD_TOKEN }} --build-arg GOOS=linux --build-arg GOARCH=arm64 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux -t ${{ env.IMAGE_NAME }}:latest-arm64-linux .

      - name: Push AMD64-linux image
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux
        

  build-arm64:
    needs: prepare
    runs-on: [self-hosted, ARM64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -f ${{ env.DOCKERFILE }} --build-arg GITHUB_TOKEN=${{ secrets.SNOOPY_DOWNLOAD_TOKEN }} --build-arg GOOS=linux --build-arg GOARCH=arm64 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-arm64 -t ${{ env.IMAGE_NAME }}:latest-arm64 .
      - name: Push ARM64 image
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-arm64
       

  build-armv7:
    needs: prepare
    runs-on: [self-hosted, ARM64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARMv7 image
        run: |
          GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2 | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          BUILD_TIMESTAMP=$(date -Iseconds)
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker build -f ${{ env.DOCKERFILE }} --build-arg GITHUB_TOKEN=${{ secrets.SNOOPY_DOWNLOAD_TOKEN }} --platform=linux/arm/v7 --build-arg GOOS=linux --build-arg GOARCH=arm --build-arg GOARM=7 --build-arg VERSION="$VERSION" --build-arg BUILD_TIMESTAMP="$BUILD_TIMESTAMP" --build-arg GIT_BRANCH="$GIT_BRANCH" --build-arg COMMIT_HASH="$COMMIT_HASH" -t ${{ env.IMAGE_NAME }}:$VERSION-arm7 -t ${{ env.IMAGE_NAME }}:latest-arm7 .
          
      - name: Push ARMv7 image
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker push ${{ env.IMAGE_NAME }}:$VERSION-arm7


  merge-images:
    if: github.ref == 'refs/heads/main'
    needs: [build-amd64, build-arm64, build-arm64-linux, build-armv7, prepare]
    runs-on: self-hosted-ansible
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge images into a multi-arch manifest
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          docker manifest create ${{ env.IMAGE_NAME }}:$VERSION \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-amd64 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm7 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:$VERSION
          docker manifest create ${{ env.IMAGE_NAME }}:latest \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-amd64 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64-linux \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm7 \
              --amend ${{ env.IMAGE_NAME }}:$VERSION-arm64
          docker manifest push ${{ env.IMAGE_NAME }}:latest
        

  helm-chart:
    if: github.ref == 'refs/heads/main'
    needs: [prepare, build-amd64, build-arm64, build-arm64-linux, build-armv7, merge-images]
    runs-on: self-hosted-ansible
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: set version env
        run: echo "SEMVERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV  

      - name: Install Helm
        uses: azure/setup-helm@v4.3.1
        id: install

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1.6.2
        with:
          chart-search-root: helm

      - name: package and push
        run: |
          cd ./helm/charts/mogenius-k8s-manager
          sed -i -e "s/v1.0.72/${{ env.SEMVERSION }}/" values.yaml
          helm package -d /tmp/ --version ${{ env.SEMVERSION }} --app-version ${{ env.SEMVERSION }} .
          curl -XPOST -L -k --data-binary "@/tmp/${{ env.HELMNAME }}-${{ env.SEMVERSION }}.tgz" https://${{ secrets.MO_HELMUSER }}:${{ secrets.MO_HELMPASS }}@helm.mogenius.com/api/public/charts
   
